# Generated by Django 6.0.4 on 2026-04-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('customer_payment_simulation', 'Customer Payment Simulation'), ('payout_hold', 'Payout Hold'), ('payout_refund', 'Payout Refund')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='payouts.merchant'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
